services:
  mysql:
    image: mysql:8.0
    container_name: chat_mysql_server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "user_app_db"
      MYSQL_USER: "user_app"
      MYSQL_PASSWORD: "Manjoor@1822"
    networks:
      - chat_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  chat_network:
