version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chat_sql_server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Manjoor@1822"
      MSSQL_PID: "Developer"
      MSSQL_DATABASE: "user_app_db"
    networks:
      - chat_network
    restart: unless-stopped

networks:
  chat_network:
